/**
 * Created by Madhu on 5/4/16.
 */
var countryT6 = [
    { name: "Afghanistan", code: "AFG"},
    { name: "Albania", code: "ALB"},
    { name: "Algeria", code: "DZA"},
    { name: "American Samoa", code: "ASM"},
    { name: "Andorra", code: "AND"},
    { name: "Angola", code: "AGO"},
    { name: "Anguilla", code: "AIA"},
    { name: "Antigua And Barbuda", code: "ATG"},
    { name: "Argentina", code: "ARG"},
    { name: "Armenia", code: "ARM"},
    { name: "Aruba", code: "ABW"},
    { name: "Australia", code: "AUS"},
    { name: "Austria", code: "AUT"},
    { name: "Azerbaijan", code: "AZE"},
    { name: "Bahamas", code: "BHS"},
    { name: "Bahrain", code: "BHR"},
    { name: "Bangladesh", code: "BGD"},
    { name: "Barbados", code: "BRB"},
    { name: "Belarus", code: "BLR"},
    { name: "Belgium", code: "BEL"},
    { name: "Belize", code: "BLZ"},
    { name: "Benin", code: "BEN"},
    { name: "Bhutan", code: "BTN"},
    { name: "Bolivia", code: "BOL"},
    { name: "Bonaire, Saint Eustatius And Saba", code: "BES"},
    { name: "Bosnia And Herzegovina", code: "BIH"},
    { name: "Botswana", code: "BWA"},
    { name: "Brazil", code: "BRA"},
    { name: "British Virgin Islands", code: "VGB"},
    { name: "Bulgaria", code: "BGR"},
    { name: "Burkina Faso", code: "BFA"},
    { name: "Burma", code: "MMR"},
    { name: "Burundi", code: "BDI"},
    { name: "CÃ´te D'Ivoire", code: "CIV"},
    { name: "Cambodia", code: "KHM"},
    { name: "Cameroon", code: "CMR"},
    { name: "Canada", code: "CAN"},
    { name: "Cape Verde", code: "CPV"},
    { name: "Cayman Islands", code: "CYM"},
    { name: "Central African Republic", code: "CAF"},
    { name: "Chad", code: "TCD"},
    { name: "Chile", code: "CHL"},
    { name: "China", code: "CHN"},
    { name: "Christmas Island", code: "CXR"},
    { name: "Colombia", code: "COL"},
    { name: "Comoros", code: "COM"},
    { name: "Congo (Democratic Republic Of The)", code: "COD"},
    { name: "Congo", code: "COG"},
    { name: "Costa Rica", code: "CRI"},
    { name: "Croatia", code: "HRV"},
    { name: "Cuba", code: "CUB"},
    { name: "Cyprus", code: "CYP"},
    { name: "Czech Republic", code: "CZE"},
    { name: "Denmark", code: "DNK"},
    { name: "Djibouti", code: "DJI"},
    { name: "Dominica", code: "DMA"},
    { name: "Dominican Republic", code: "DOM"},
    { name: "Ecuador", code: "ECU"},
    { name: "Egypt", code: "EGY"},
    { name: "El Salvador", code: "SLV"},
    { name: "Equatorial Guinea", code: "GNQ"},
    { name: "Eritrea", code: "ERI"},
    { name: "Estonia", code: "EST"},
    { name: "Ethiopia", code: "ETH"},
    { name: "Falkland Islands (Islas Malvinas)", code: "FLK"},
    { name: "Faroe Islands", code: "FRO"},
    { name: "Fiji", code: "FJI"},
    { name: "Finland", code: "FIN"},
    { name: "France", code: "FRA"},
    { name: "French Guiana", code: "GUF"},
    { name: "French Polynesia", code: "PYF"},
    { name: "Gabon", code: "GAB"},
    { name: "Gambia", code: "GMB"},
    { name: "Georgia", code: "GEO"},
    { name: "Germany", code: "DEU"},
    { name: "Ghana", code: "GHA"},
    { name: "Greece", code: "GRC"},
    { name: "Greenland", code: "GRL"},
    { name: "Grenada", code: "GRD"},
    { name: "Guadeloupe", code: "GLP"},
    { name: "Guatemala", code: "GTM"},
    { name: "Guernsey", code: "GGY"},
    { name: "Guinea Bissau", code: "GNB"},
    { name: "Guinea", code: "GIN"},
    { name: "Guyana", code: "GUY"},
    { name: "Haiti", code: "HTI"},
    { name: "Honduras", code: "HND"},
    { name: "Hong Kong", code: "HKG"},
    { name: "Hungary", code: "HUN"},
    { name: "Iceland", code: "ISL"},
    { name: "India", code: "IND"},
    { name: "Indonesia", code: "IDN"},
    { name: "Iran", code: "IRN"},
    { name: "Iraq", code: "IRQ"},
    { name: "Ireland", code: "IRL"},
    { name: "Isle Of Man", code: "IMN"},
    { name: "Israel", code: "ISR"},
    { name: "Italy", code: "ITA"},
    { name: "Jamaica", code: "JAM"},
    { name: "Japan", code: "JPN"},
    { name: "Jersey", code: "JEY"},
    { name: "Jordan", code: "JOR"},
    { name: "Kazakhstan", code: "KAZ"},
    { name: "Kenya", code: "KEN"},
    { name: "Kiribati", code: "KIR"},
    { name: "Kuwait", code: "KWT"},
    { name: "Kyrgyzstan", code: "KGZ"},
    { name: "Laos", code: "LAO"},
    { name: "Latvia", code: "LVA"},
    { name: "Lebanon", code: "LBN"},
    { name: "Lesotho", code: "LSO"},
    { name: "Liberia", code: "LBR"},
    { name: "Libya", code: "LBY"},
    { name: "Liechtenstein", code: "LIE"},
    { name: "Lithuania", code: "LTU"},
    { name: "Luxembourg", code: "LUX"},
    { name: "Macau", code: "MAC"},
    { name: "Macedonia", code: "MKD"},
    { name: "Madagascar", code: "MDG"},
    { name: "Malawi", code: "MWI"},
    { name: "Malaysia", code: "MYS"},
    { name: "Mali", code: "MLI"},
    { name: "Malta", code: "MLT"},
    { name: "Martinique", code: "MTQ"},
    { name: "Mauritania", code: "MRT"},
    { name: "Mauritius", code: "MUS"},
    { name: "Mayotte", code: "MYT"},
    { name: "Mexico", code: "MEX"},
    { name: "Moldova", code: "MDA"},
    { name: "Monaco", code: "MCO"},
    { name: "Mongolia", code: "MNG"},
    { name: "Montenegro", code: "MNE"},
    { name: "Montserrat", code: "MSR"},
    { name: "Morocco", code: "MAR"},
    { name: "Mozambique", code: "MOZ"},
    { name: "Namibia", code: "NAM"},
    { name: "Nepal", code: "NPL"},
    { name: "Netherlands", code: "NLD"},
    { name: "New Caledonia", code: "NCL"},
    { name: "New Zealand", code: "NZL"},
    { name: "Nicaragua", code: "NIC"},
    { name: "Niger", code: "NER"},
    { name: "Nigeria", code: "NGA"},
    { name: "Niue", code: "NIU"},
    { name: "North Korea", code: "PRK"},
    { name: "Norway", code: "NOR"},
    { name: "Oman", code: "OMN"},
    { name: "Pakistan", code: "PAK"},
    { name: "Palestina", code: "PSE"},
    { name: "Panama", code: "PAN"},
    { name: "Papua New Guinea", code: "PNG"},
    { name: "Paraguay", code: "PRY"},
    { name: "Peru", code: "PER"},
    { name: "Philippines", code: "PHL"},
    { name: "Poland", code: "POL"},
    { name: "Portugal", code: "PRT"},
    { name: "Puerto Rico", code: "PRI"},
    { name: "Qatar", code: "QAT"},
    { name: "Reunion", code: "REU"},
    { name: "Romania", code: "ROU"},
    { name: "Russia", code: "RUS"},
    { name: "Rwanda", code: "RWA"},
    { name: "Saint Kitts And Nevis", code: "KNA"},
    { name: "Saint Lucia", code: "LCA"},
    { name: "Saint Pierre And Miquelon", code: "SPM"},
    { name: "Saint Vincent And The Grenadines", code: "VCT"},
    { name: "Samoa", code: "WSM"},
    { name: "San Marino", code: "SMR"},
    { name: "Sao Tome And Principe", code: "STP"},
    { name: "Saudi Arabia", code: "SAU"},
    { name: "Senegal", code: "SEN"},
    { name: "Serbia", code: "SRB"},
    { name: "Seychelles", code: "SYC"},
    { name: "Sierra Leone", code: "SLE"},
    { name: "Singapore", code: "SGP"},
    { name: "Sint Maarten", code: "SXM"},
    { name: "Slovakia", code: "SVK"},
    { name: "Slovenia", code: "SVN"},
    { name: "Solomon Islands", code: "SLB"},
    { name: "Somalia", code: "SOM"},
    { name: "South Africa", code: "ZAF"},
    { name: "South Georgia And The South Sandwich Isla", code: "SGS"},
    { name: "South Korea", code: "KOR"},
    { name: "Spain", code: "ESP"},
    { name: "Sri Lanka", code: "LKA"},
    { name: "Sudan", code: "SDN"},
    { name: "Suriname", code: "SUR"},
    { name: "Svalbard And Jan Mayen", code: "SJM"},
    { name: "Swaziland", code: "SWZ"},
    { name: "Sweden", code: "SWE"},
    { name: "Switzerland", code: "CHE"},
    { name: "Syria", code: "SYR"},
    { name: "Taiwan", code: "TWN"},
    { name: "Tajikistan", code: "TJK"},
    { name: "Tanzania", code: "TZA"},
    { name: "Thailand", code: "THA"},
    { name: "Timor Leste", code: "TLS"},
    { name: "Togo", code: "TGO"},
    { name: "Tonga", code: "TON"},
    { name: "Trinidad And Tobago", code: "TTO"},
    { name: "Tunisia", code: "TUN"},
    { name: "Turkey", code: "TUR"},
    { name: "Turkmenistan", code: "TKM"},
    { name: "Turks And Caicas Islands", code: "TCA"},
    { name: "Uganda", code: "UGA"},
    { name: "Ukraine", code: "UKR"},
    { name: "United Arab Emirates", code: "ARE"},
    { name: "United Kingdom", code: "GBR"},
    { name: "United States", code: "USA"},
    { name: "Uruguay", code: "URY"},
    { name: "Uzbekistan", code: "UZB"},
    { name: "Venezuela", code: "VEN"},
    { name: "Vietnam", code: "VNM"},
    { name: "Western Sahara", code: "ESH"},
    { name: "Yemen", code: "YEM"},
    { name: "Zambia", code: "ZMB"},
    { name: "Zimbabwe", code: "ZWE"},
    { name: "Palau", code: "PLW"},
    { name: "Federated States Of Micronesia", code: "FSM"},
    { name: "Guam", code: "GUM"},
    { name: "Northern Mariana Islands", code: "MNP"},
    { name: "French Southern And Antarctic Lands", code: "ATF"},
    { name: "Heard Island And Mcdonald Islands", code: "HMD"}
]

var selectCountryT6 = document.getElementById("selectCountryT6");
var i;
for ( i = 0; i < countryT6.length; i++) {
    var cname6 = countryT6[i].name;
    var cop6 = document.createElement("option");
    cop6.textContent = cname6;
    cop6.value = countryT6[i].code;
    selectCountryT6.appendChild(cop6);
}

if(i== countryT6.length){
    multiLineMaker();
}

